import { requireUser } from "@/lib/session"
import { canUploadBilling } from "@/lib/permissions"
import { getAuthorizedSchemes, getCollectionPeriods } from "@/app/actions/billing"
import { BillingImportClient } from "./billing-import-client"
import { AlertCircle } from "lucide-react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { PageHeader } from "@/components/ui/page-header"
import { EmptyState } from "@/components/ui/empty-state"

export default async function BillingUploadPage() {
  const current = await requireUser()
  if (!canUploadBilling(current)) {
    throw new Error("Unauthorized")
  }

  const [schemes, periods] = await Promise.all([
    getAuthorizedSchemes(),
    getCollectionPeriods(),
  ])

  if (periods.length === 0) {
    return (
      <EmptyState
        icon={AlertCircle}
        title="No Billing Periods Available"
        description="A billing period must be created by an administrator before you can import any billing data."
        action={
          <Button asChild variant="outline" className="h-11">
            <Link href="/dashboard/billing">Return to Billing Management</Link>
          </Button>
        }
        className="min-h-[400px]"
      />
    )
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="Import Monthly Billing"
        description="Upload the monthly billing export generated by the external billing system."
      />

      <BillingImportClient schemes={schemes} periods={periods} />
    </div>
  )
}
