import { requireUser } from "@/lib/session"
import { canUploadBilling } from "@/lib/permissions"
import { getAuthorizedSchemes, getCollectionPeriods } from "@/app/actions/billing"
import { BillingImportClient } from "./billing-import-client"
import { AlertCircle } from "lucide-react"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export default async function BillingUploadPage() {
  const current = await requireUser()
  if (!canUploadBilling(current)) {
    throw new Error("Unauthorized")
  }

  const [schemes, periods] = await Promise.all([
    getAuthorizedSchemes(),
    getCollectionPeriods(),
  ])

  if (periods.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] space-y-4">
        <AlertCircle className="h-12 w-12 text-amber-500" />
        <h1 className="text-xl font-bold">No Billing Periods Available</h1>
        <p className="text-muted-foreground text-center max-w-sm">
          A billing period must be created by an administrator before you can import any billing data.
        </p>
        <Button asChild variant="outline">
          <Link href="/dashboard/billing">Return to Billing Management</Link>
        </Button>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Import Monthly Billing</h1>
        <p className="text-muted-foreground">
          Upload the monthly billing export generated by the external billing system.
        </p>
      </div>

      <BillingImportClient schemes={schemes} periods={periods} />
    </div>
  )
}
